### ISSUE TITLE
Memory efficiency issue about the kernel map 

### ISSUE THREAD

**Issue by SUZhaoyu** [mit-han-lab/torchsparse#11]
Hi, I am curious about the implementations of the kernel map. Say we have 8192 valid convolution kernels, and the number of occupied voxels in each kernel is 8, then the total size of input in the kernel map is `8192*8*C_in`, and the corresponding kernel is `8192*8*C_in*C_out`. When `C_in=32` and `C_out=64`, the total memory expense is 512MB for the current input instance, and when it comes to the batch of size 16, the total memory expense is huge. May I know how did you overcome this issue? Thanks.

**Comment by kentangSJTU** [comment]
Hello,

Thanks for the interest! 

First, the total size of input in the kernel map if `8192*8*C_in`, but we actually observe that the memory space can be reused to store these inputs, and the memory requirement will go down to `8192*C_in` for input storage (since the sub kernel map corresponding to offset 0, 0, 0 is the largest).

Second, we don't have specialized kernel for each input point. If you have just 8192 input points, and the kernel size is 2, the kernel will take up `8 * C_in * C_out` memory, which is small.

Best,
Haotian

**Comment by SUZhaoyu** [comment]
Thanks for the reply @kentangSJTU , if I've got this right, you actually store the kernel map with pointers or indexes instead of using the raw data matrix right? If this is the case, how did you perform the GEMM for convolution efficiently? Or you implemented your own matrix multiply in the gpu kernels? 

Regards,
Tony

**Comment by kentangSJTU** [comment]
Hi @SUZhaoyu,

Sorry for the delayed response. Yes, your understanding is correct, we store the kernel map with indices instead of the raw data. As for the GEMM efficiency, we have customized implementation where input point with the same kernel offset are grouped together first, then we call `torch::mm_out` backend, and finally scattered the output to corresponding locations as indicated by the kernel map. Please check [here](torchsparse/src/convolution/convolution.cpp) for detail.


Best,
Haotian

**Comment by SUZhaoyu** [comment]
Thanks @kentangSJTU , understood. Appreciate a lot.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to the inactivity. Please feel free to reopen it if the problem has not been resolved.
