### ISSUE TITLE
Not support DDP training

### ISSUE THREAD

**Issue by pycoco** [mit-han-lab/torchsparse#281]
after torch.nn.SyncBatchNorm.convert_sync_batchnorm(model), get error: AttributeError: 'SparseTensor' object has no attribute 'dim'

**Comment by ys-2020** [comment]
Hi! You may need to change the function calling when refer to the dimension of the `SparseTensor`. For example, you can use `SparseTensor.C.shape` to get the coordinates' shape and `SparseTensor.F.shape` to get the feature shape. This is because `SparseTensor` has more complicated wrapper to record the information of sparsity, compared to the dense tensor.

**Comment by ys-2020** [comment]
Close as completed due to inactivity. If you have further questions, please feel free to reopen it.

**Comment by barzanisar** [comment]
Hey, I am getting the same error when training with multiple GPUS. How can we sync batch norm for sparse tensors?  Does torchsparse have its own version of SyncBatchNorm.convert_sync_batchnorm(model)?

**Comment by francotheengineer** [comment]
Fix here: 

https://github.com/mit-han-lab/torchsparse/issues/107#issuecomment-2671832997
