### ISSUE TITLE
Name change between versions? Unable to "from torchsparse.utils.kernel_region import *"

### ISSUE THREAD

**Issue by HeCraneChen** [mit-han-lab/torchsparse#94]
Hello, I'm still trying to use your package 1.4.0 when running Neural Recon. But it seems like you have moved some functions between versions. Now I'm unable to use "from torchsparse.utils.kernel_region import *" any more. There's a function named KernelRegion I need in particular. Could you please let me know how to call this function in the most recent version of TorchSparse? Thanks

**Comment by CCInc** [comment]
Hi,

KernelRegion is deprecated in 1.4.0. You should find similar functionality in `from torchsparse.nn.utils import get_kernel_offsets`. In fact, it looks like the latest version of NeuralRecon has been updated to support torchsparse 1.4. Otherwise, I would suggest using a previous version of this library.

**Comment by HeCraneChen** [comment]
Thanks! It works now, it's my fault not updating NeuralRecon in time.
